# Generated by Django 6.0 on 2025-12-09 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Clinician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinician_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinicians",
                        to="clinical.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="Contact email for the patient. Not necessarily unique.",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to user account for patient portal access.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PatientClinician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this clinician is the primary clinician for the patient.",
                    ),
                ),
                ("relationship_start", models.DateTimeField()),
                (
                    "relationship_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null means the relationship is still active.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "clinician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_clinician_links",
                        to="clinical.clinician",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_clinician_links",
                        to="clinical.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Clinician Link",
                "verbose_name_plural": "Patient Clinician Links",
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="clinicians",
            field=models.ManyToManyField(
                blank=True,
                related_name="patients",
                through="clinical.PatientClinician",
                to="clinical.clinician",
            ),
        ),
        migrations.AddIndex(
            model_name="clinician",
            index=models.Index(fields=["name"], name="clinical_cl_name_2c25b1_idx"),
        ),
        migrations.AddIndex(
            model_name="patientclinician",
            index=models.Index(
                fields=["patient", "clinician"], name="clinical_pa_patient_043ac9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientclinician",
            index=models.Index(
                fields=["clinician", "relationship_end"],
                name="clinical_pa_clinici_c816f5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientclinician",
            constraint=models.UniqueConstraint(
                fields=("patient", "clinician", "relationship_start"),
                name="uniq_patient_clinician_start",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["name"], name="clinical_pa_name_601001_idx"),
        ),
    ]
