# Generated by Django 6.0 on 2025-12-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinician",
            options={"ordering": ["name", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["name", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Contact email for the patient.",
                max_length=254,
                null=True,
            ),
        ),
    ]
