# Generated by Django 6.0 on 2025-12-09 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom name; if blank, use the procedure type name.",
                        max_length=255,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If null, Services may fall back to the procedure type duration default.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("VOID", "Void"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "clinician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedures",
                        to="clinical.clinician",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedures",
                        to="clinical.patient",
                    ),
                ),
                (
                    "procedure_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedures",
                        to="catalog.proceduretype",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["scheduled_at"], name="scheduling__schedul_2fac55_idx"
                    ),
                    models.Index(
                        fields=["status"], name="scheduling__status_3368fe_idx"
                    ),
                    models.Index(
                        fields=["clinician", "scheduled_at"],
                        name="scheduling__clinici_fab2f0_idx",
                    ),
                ],
            },
        ),
    ]
