# Generated by Django 6.0 on 2025-12-09 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this procedure type (e.g. internal or billing code).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "default_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional default duration for this procedure type.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False to retire this type from new procedures.",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional department that typically owns this procedure.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedure_types",
                        to="clinical.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="catalog_pro_name_c97b0d_idx"),
                    models.Index(fields=["code"], name="catalog_pro_code_d1e299_idx"),
                ],
            },
        ),
    ]
