# Generated by Django 6.0 on 2025-12-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proceduretype",
            options={"ordering": ["name", "-created_at"]},
        ),
    ]
